CSS.OpusForce.UI.Web.MVC/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CSS.OpusForce.Services.Interfaces;
using CSS.OpusForce.Services.Messaging;
using CSS.OpusForce.Services.ViewModels;

namespace CSS.OpusForce.UI.Web.MVC.Controllers
{ 
    public class CompanyController : Controller
    {
        private readonly ICompanyServices _companyService;        

        public CompanyController(ICompanyServices companyService)
        {
            _companyService = companyService;

            ResetInfoMessages();
        }

        private void ResetInfoMessages()
        {
            if (TempData["Error"] == null)
                TempData["Error"] = string.Empty;
            if (TempData["Add"] == null)
                TempData["Add"] = false;
            if (TempData["Update"] == null)
                TempData["Update"] = false;
            if (TempData["Delete"] == null)
                TempData["Delete"] = false;
        }

        /*******************************************************************/
        /*                      Company Actions                            */
        /*******************************************************************/
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult CompanyList()
        {
            // 1. Get Company list
            // 2. View CompanyList (Grid)

            ResetInfoMessages();

            ListCompaniesResponse response = _companyService.ListCompanies(null);
            return View(response.Companies);
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult CompanyCreate()
        {
            // 1. View CompanyCreate (Empty Form)

            ResetInfoMessages();

            var companyTypes = _companyService.ListCompanyTypes(null).CompanyTypes.OrderBy(c => c.Name);
            var companyTypeList = new SelectList(companyTypes, "Id", "Name");
            TempData["CompanyTypes"] = companyTypeList;

            var companies = _companyService.ListCompanies(null).Companies.OrderBy(c => c.Name);
            var companyList = new SelectList(companies, "Id", "Name");
            TempData["Companies"] = companyList;

            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult CompanyCreate(CompanyView view)
        {
            // 1. If ModelState is not valid
            // ------------------------------
            // 1.1. View CompanyCreate (Empty Form)
            // 1.2. Enable ValidationSummary
            // ------------------------------
            // 2. If ExceptionState is true
            // ------------------------------
            // 2.1. View CompanyCreate (Empty Form)
            // 2.2. Enable ErrorBox
            // ------------------------------
            // 3. Set Add to true
            // 4. View CompanyRead
            // 5. View SuccessBox

            ResetInfoMessages();

            var companyTypes = _companyService.ListCompanyTypes(null).CompanyTypes.OrderBy(c => c.Name);
            var companyTypeList = new SelectList(companyTypes, "Id", "Name");
            TempData["CompanyTypes"] = companyTypeList;

            var companies = _companyService.ListCompanies(null).Companies.OrderBy(c => c.Name);
            var companyList = new SelectList(companies, "Id", "Name");
            TempData["Companies"] = companyList;

            if (ModelState.IsValid)
            {
                CreateCompanyRequest request = new CreateCompanyRequest();
                request.Name = view.Name;
                request.Description = view.Description;
                request.IsActive = view.IsActive;
                request.CompanyTypeId = view.CompanyTypeId;
                request.ParentCompanyId = (int?) view.ParentCompanyId;

                CreateCompanyResponse response = _companyService.CreateCompany(request);

                if (response.ExceptionState)
                {
                    TempData["Error"] = response.ExceptionMessage;
                    return View();
                }

                TempData["Add"] = true;
                return View("CompanyRead", response.Company);
            }
            else
            {
                return View();
            }  
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult CompanyRead(int id)
        {
            // 1. Get Company (by Id)
            // 2. View CompanyRead

            ResetInfoMessages();

            ReadCompanyRequest request = new ReadCompanyRequest();
            request.Id = id;

            ReadCompanyResponse response = new ReadCompanyResponse();
            response = _companyService.ReadCompany(request);

            return View("CompanyRead", response.Company);
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult CompanyUpdate(int id)
        {
            // 1. Get Company (by Id)
            // 2. View Company (Filled Form)

            ResetInfoMessages();

            ReadCompanyRequest request = new ReadCompanyRequest();
            request.Id = id;

            ReadCompanyResponse response = new ReadCompanyResponse();
            response = _companyService.ReadCompany(request);

            var companyTypes = _companyService.ListCompanyTypes(null).CompanyTypes.OrderBy(c => c.Name);
            var companyTypeList = new SelectList(companyTypes, "Id", "Name", response.Company.CompanyTypeId);
            TempData["CompanyTypes"] = companyTypeList;

            var companies = _companyService.ListCompanies(null).Companies.OrderBy(c => c.Name);
            var companyList = new SelectList(companies, "Id", "Name", response.Company.ParentCompanyId);
            TempData["Companies"] = companyList;

            return View(response.Company);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult CompanyUpdate(CompanyView view)
        {
            // 1. If ModelState is not valid
            // ------------------------------
            // 1.1. View CompanyUpdate (Filled Form)
            // 1.2. Enable ValidationSummary
            // ------------------------------
            // 2. If ExceptionState is true
            // ------------------------------
            // 2.1. View CompanyUpdate (Filled Form)
            // 2.2. Enable ErrorBox
            // ------------------------------
            // 3. Set Update to true
            // 4. View CompanyRead
            // 5. View SuccessBox

            ResetInfoMessages();

            var companyTypes = _companyService.ListCompanyTypes(null).CompanyTypes.OrderBy(c => c.Name);
            var companyTypeList = new SelectList(companyTypes, "Id", "Name", view.CompanyTypeId);
            TempData["CompanyTypes"] = companyTypeList;

            var companies = _companyService.ListCompanies(null).Companies.OrderBy(c => c.Name);
            var companyList = new SelectList(companies, "Id", "Name", view.ParentCompanyId);
            TempData["Companies"] = companyList;

            if (ModelState.IsValid)
            {
                UpdateCompanyRequest request = new UpdateCompanyRequest();
                request.Id = view.Id;
                request.Name = view.Name;
                request.Description = view.Description;
                request.IsActive = view.IsActive;
                request.CompanyTypeId = view.CompanyTypeId;
                request.ParentCompanyId = (int?) view.ParentCompanyId;

                UpdateCompanyResponse response = _companyService.UpdateCompany(request);

                if (response.ExceptionState)
                {
                    TempData["Error"] = response.ExceptionMessage;
                    return View(view);
                }

                TempData["Update"] = true;
                return View("CompanyRead", response.Company);
            }
            else
            {
                return View(view);
            }
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult CompanyDelete(int id)
        {
            // 1. Try delete record
            // 2. If ExceptionState is true
            // ------------------------------
            // 2.1. View CompanyList
            // 2.2. Enable ErrorBox
            // ------------------------------
            // 3. Delete record
            // 4. Set Delete to true
            // 5. View CompanyList

            ResetInfoMessages();

            DeleteCompanyRequest request = new DeleteCompanyRequest();
            request.Id = id;

            DeleteCompanyResponse response = new DeleteCompanyResponse();
            response = _companyService.DeleteCompany(request);

            if (response.ExceptionState)
            {
                TempData["Error"] = response.ExceptionMessage;
                return View("CompanyList", response.Companies);
            }

            TempData["Delete"] = true;
            return RedirectToAction("CompanyList");
        }
        /*******************************************************************/
        /*                    CompanyType Actions                          */
        /*******************************************************************/
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult CompanyTypeList()
        {
            // 1. Get CompanyType list
            // 2. View CompanyTypeList (Grid)

            ResetInfoMessages();

            ListCompanyTypesResponse response = _companyService.ListCompanyTypes(null);
            return View(response.CompanyTypes);
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult CompanyTypeCreate()
        {
            // 1. View CompanyTypeCreate (Empty Form)

            ResetInfoMessages();


CSS.OpusForce.UI.Web.MVC/Views/Company/CompanyCreate.cshtml
@using CSS.OpusForce.Services.ViewModels;
@model CompanyView

@{
    ViewBag.Title = "Firma Ekleme";
    Layout = "~/Views/Shared/_Layout.cshtml";   
}

<script type="text/javascript">
    $(function () {
        $('form.uniForm').uniform({
            prevent_submit: true
        });
    });
</script>

<div id="header-band" class="bg-blue">    
   @Html.ActionLink("Firmalar", "CompanyList", "Company", null, new { Class = "btnBack" })
   @Html.ActionLink("Anasayfa", "Index", "Home", null, new { Class = "btnHome" })   
   <div class="ym-wrapper">
       <div class="ym-grid top-35">
           <div class="ym-gl">
               <img alt="OpusForce Logo" src="@Url.Content("~/Content/images/logo.png")" />
           </div>
           <div class="ym-gr">
               @Html.ActionLink("Home", "Index", "Home", null, new { Class = "btnLogin" })
           </div>
       </div> 
   </div>           
</div>
<div class="clearfix"></div>
<div id="main">
    <div class="ym-wrapper">   
        <div class="ym-hlist">
          <ul>
            <li class="active">@Html.ActionLink("Firmalar", "CompanyList", "Company", null, null)</li>
            <li>@Html.ActionLink("Firma Faaliyet Alanları", "CompanyTypeList", "Company", null, null)</li>
          </ul>
        </div>
        <hr />
        @using (Html.BeginForm(null, null, FormMethod.Post, new { Class="ym-form ym-columnar" }))
        {   
            @Html.ValidationSummary() 
            
            if (!String.IsNullOrEmpty((string)TempData["Error"]))
            {
                <p class="box error">@TempData["Error"]</p>
                <hr />
            }
            
            <div class="ym-fbox-text">
                <label for="Name">Firma Adı</label>
                @Html.TextBoxFor(c => c.Name)
            </div>
            
            <div class="ym-fbox-text">
                <label for="Description">Firma Açıklaması</label>
                @Html.TextAreaFor(c => c.Description, new { rows = "5" })
            </div>
            
            <div class="ym-fbox-check">
                @Html.CheckBoxFor(c => c.IsActive)
                <label for="IsActive">Firma Aktif Mi?</label>
            </div>
            
            <div class="ym-fbox-select">
                <label for="CompanyTypeId">Firma Faaliyet Alanı</label>
                @Html.DropDownListFor(c => c.CompanyTypeId, (SelectList)TempData["CompanyTypes"], "-Seçiniz-")
            </div>
            
            <div class="ym-fbox-select">
                <label for="ParentCompanyId">Bağlı Olduğu Firma</label>
                @Html.DropDownListFor(c => c.ParentCompanyId, (SelectList)TempData["Companies"], "-Seçiniz-")
            </div>
    
            <div class="ym-fbox-button">
                @Html.ActionLink("Vazgeç ve geri dön", "CompanyList", "Company", null, new { Class = "ym-button ym-left-arrow" }) 
                <button class="ym-button ym-add">Kaydet</button>
            </div>   
        }        
    </div>
</div>

CSS.OpusForce.UI.Web.MVC/Views/Company/CompanyList.cshtml
@using CSS.OpusForce.Services.ViewModels;
@model IEnumerable<CompanySummaryView>
           
@{
    ViewBag.Title = "Firma Listesi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="header-band" class="bg-blue">    
    @Html.ActionLink("Firmalar", "CompanyList", "Company", null, new { Class = "btnBack" })
    @Html.ActionLink("Anasayfa", "Index", "Home", null, new { Class = "btnHome" })   
    <div class="ym-wrapper">
        <div class="ym-grid top-35">
            <div class="ym-gl">
                <img alt="OpusForce Logo" src="@Url.Content("~/Content/images/logo.png")" />
            </div>
            <div class="ym-gr">
                @Html.ActionLink("Home", "Index", "Home", null, new { Class = "btnLogin" })
            </div>
        </div> 
    </div>           
</div>
<div class="clearfix"></div>
<div id="main">
    <div class="ym-wrapper">        
        <div class="ym-hlist">
          <ul>
            <li class="active">@Html.ActionLink("Firmalar", "CompanyList", "Company", null, null)</li>
            <li>@Html.ActionLink("Firma Faaliyet Alanları", "CompanyTypeList", "Company", null, null)</li>
          </ul>
        </div>
        <hr />

        @if (!String.IsNullOrEmpty((string)TempData["Error"]))
        {
            <p class="box error">@TempData["Error"]</p>
            <hr />
        }
        @if ((bool)TempData["Delete"])
        {
            <p class="box warning">Tebrikler! Kayıt Başarıyla Silindi.</p>
            <hr />
        }
        
        @(Html.Telerik().Grid(Model)
            .Name("Companies")
            .DataKeys(dataKeys => dataKeys.Add(c => c.Id))
            .DataBinding(dataBinding => dataBinding.Server()
                .Delete("CompanyDelete", "Company", null))
            .Columns(columns =>
            {
                columns.Bound(o => o.Id).Title("No.").Width(10);
                columns.Bound(o => o.Name).Title("Firma Adı");
                columns.Bound(o => o.CompanyTypeName).Title("Ana Faaliyet Konusu");
                columns.Bound(o => o.ParentCompanyName).Title("Bağlı Olduğu Firma");
                columns.Bound(o => o.IsActive).Title("Durumu");
                columns.Command(commands =>
                {
                    commands.Custom("viewDetails")
                    .Text("Detay")
                    .Ajax(false)
                    .Action("CompanyRead", "Company", null);
                    commands.Delete().ButtonType(GridButtonType.ImageAndText);
                })
                .Width(200);
            })
            .Sortable()
            .Pageable(paging => paging.PageSize(10))
            .Localizable("tr-TR")
            ) 

        @Html.ActionLink("Firma Oluştur", "CompanyCreate", null, new { Class = "ym-button ym-add" })
    </div>
</div>

CSS.OpusForce.UI.Web.MVC/Views/Company/CompanyRead.cshtml
@using CSS.OpusForce.Services.ViewModels;
@model CompanyView

@{
    ViewBag.Title = "Firma Detay";
    Layout = "~/Views/Shared/_Layout.cshtml";   
}

<div id="header-band" class="bg-blue">    
   @Html.ActionLink("Firmalar", "CompanyList", "Company", null, new { Class = "btnBack" })
   @Html.ActionLink("Anasayfa", "Index", "Home", null, new { Class = "btnHome" })   
   <div class="ym-wrapper">
       <div class="ym-grid top-35">
           <div class="ym-gl">
               <img alt="OpusForce Logo" src="@Url.Content("~/Content/images/logo.png")" />
           </div>
           <div class="ym-gr">
               @Html.ActionLink("Home", "Index", "Home", null, new { Class = "btnLogin" })
           </div>
       </div> 
   </div>           
</div>
<div class="clearfix"></div>
<div id="main">
    <div class="ym-wrapper">   
        <div class="ym-hlist">
          <ul>
            <li class="active">@Html.ActionLink("Firmalar", "CompanyList", "Company", null, null)</li>
            <li>@Html.ActionLink("Firma Faaliyet Alanları", "CompanyTypeList", "Company", null, null)</li>
          </ul>
        </div>
        <hr />

        @if ((bool)TempData["Add"])
        {
            <p class="box success">Tebrikler! Kayıt Başarıyla Oluşturuldu.</p>
            <hr />
        }
        @if ((bool)TempData["Update"])
        {
            <p class="box success">Tebrikler! Kayıt Başarıyla Güncelleştirildi.</p>
            <hr />
        }
        
        <div class="ym-grid ym-gbox">
            <div class="ym-g38 ym-gl"><b>Firma No.</b></div><div class="ym-g62 ym-gr">: @Model.Id</div>
        </div>
        <div class="ym-grid">
            <hr class="thick" />
        </div>
        <div class="ym-grid ym-gbox">
            <div class="ym-g38 ym-gl"><b>Firma Adı</b></div><div class="ym-g62 ym-gr">: @Model.Name</div>
        </div>
        <div class="ym-grid">
            <hr class="thick" />
        </div>
        <div class="ym-grid ym-gbox">
            <div class="ym-g38 ym-gl"><b>Firma Açıklaması</b></div><div class="ym-g62 ym-gr">: @Model.Description</div>
        </div>
        <div class="ym-grid">
            <hr class="thick" />
        </div>
        <div class="ym-grid ym-gbox">
            <div class="ym-g38 ym-gl"><b>Firma Aktif Mi?</b></div><div class="ym-g62 ym-gr">: @(Model.IsActive ? "Evet" : "Hayır")</div>
        </div>
        <div class="ym-grid">
            <hr class="thick" />
        </div>
        <div class="ym-grid ym-gbox">
            <div class="ym-g38 ym-gl"><b>Firma Faaliyet Alanı</b></div><div class="ym-g62 ym-gr">: @Model.CompanyTypeName</div>
        </div>
        <div class="ym-grid">
            <hr class="thick" />
        </div>
        <div class="ym-grid ym-gbox">
            <div class="ym-g38 ym-gl"><b>Bağlı Olduğu Firma</b></div><div class="ym-g62 ym-gr">: @Model.ParentCompanyName</div>
        </div>
        <div class="ym-grid">
            <hr class="thick" />
        </div>
        <div class="ym-grid">
             @Html.ActionLink("Geri dön", "CompanyList", "Company", null, new { Class = "ym-button ym-left-arrow" })
             @Html.ActionLink("Düzenle", "CompanyUpdate", "Company", new { id = Model.Id }, new { Class = "ym-button ym-edit" })
        </div>        
    </div>
</div>

CSS.OpusForce.UI.Web.MVC/Views/Company/CompanyTypeCreate.cshtml
@using CSS.OpusForce.Services.ViewModels;
@model CompanyTypeView

@{
    ViewBag.Title = "Firma Faaliyet Alanı Ekleme";
    Layout = "~/Views/Shared/_Layout.cshtml";   
}

<script type="text/javascript">
    $(function () {
        $('form.uniForm').uniform({
            prevent_submit: true
        });
    });
</script>

<div id="header-band" class="bg-blue">    
   @Html.ActionLink("Firmalar", "CompanyTypeList", "Company", null, new { Class = "btnBack" })
   @Html.ActionLink("Anasayfa", "Index", "Home", null, new { Class = "btnHome" })   
   <div class="ym-wrapper">
       <div class="ym-grid top-35">
           <div class="ym-gl">
               <img alt="OpusForce Logo" src="@Url.Content("~/Content/images/logo.png")" />
           </div>
           <div class="ym-gr">
               @Html.ActionLink("Home", "Index", "Home", null, new { Class = "btnLogin" })
           </div>
       </div> 
   </div>           
</div>
<div class="clearfix"></div>
<div id="main">
    <div class="ym-wrapper">   
        <div class="ym-hlist">
          <ul>
            <li>@Html.ActionLink("Firmalar", "CompanyList", "Company", null, null)</li>
            <li class="active">@Html.ActionLink("Firma Faaliyet Alanları", "CompanyTypeList", "Company", null, null)</li>
          </ul>
        </div>
        <hr />
        @using (Html.BeginForm(null, null, FormMethod.Post, new { Class="ym-form ym-columnar" }))
        {   
            @Html.ValidationSummary() 
            
            if (!String.IsNullOrEmpty((string)TempData["Error"]))
            {
                <p class="box error">@TempData["Error"]</p>
                <hr />
            }
            
            <div class="ym-fbox-text">
                <label for="Name">Faaliyet Alan Adı</label>
                @Html.TextBoxFor(c => c.Name)
            </div>
            
            <div class="ym-fbox-text">
                <label for="Description">Faaliyet Alanı Açıklaması</label>
                @Html.TextAreaFor(c => c.Description, new { rows = "5" })
            </div>
    
            <div class="ym-fbox-button">
                @Html.ActionLink("Vazgeç ve geri dön", "CompanyTypeList", "Company", null, new { Class = "ym-button ym-left-arrow" }) 
                <button class="ym-button ym-add">Kaydet</button>
            </div>   
        }        
    </div>
</div>

CSS.OpusForce.UI.Web.MVC/Views/Company/CompanyTypeList.cshtml
@using CSS.OpusForce.Services.ViewModels;
@model IEnumerable<CompanyTypeSummaryView>

@{
    ViewBag.Title = "Firma Ana Faaliyet Alanları Listesi";
    Layout = "~/Views/Shared/_Layout.cshtml";   
}

<div id="header-band" class="bg-blue">    
   @Html.ActionLink("Firmalar", "CompanyTypeList", "Company", null, new { Class = "btnBack" })
   @Html.ActionLink("Anasayfa", "Index", "Home", null, new { Class = "btnHome" })   
   <div class="ym-wrapper">
       <div class="ym-grid top-35">
           <div class="ym-gl">
               <img alt="OpusForce Logo" src="@Url.Content("~/Content/images/logo.png")" />
           </div>
           <div class="ym-gr">
               @Html.ActionLink("Home", "Index", "Home", null, new { Class = "btnLogin" })
           </div>
       </div> 
   </div>           
</div>
<div class="clearfix"></div>
<div id="main">
    <div class="ym-wrapper">        
        <div class="ym-hlist">
          <ul>
            <li>@Html.ActionLink("Firmalar", "CompanyList", "Company", null, null)</li>
            <li class="active">@Html.ActionLink("Firma Faaliyet Alanları", "CompanyTypeList", "Company", null, null)</li>
          </ul>
        </div>
        <hr />

        @if (!String.IsNullOrEmpty((string)TempData["Error"]))
        {
            <p class="box error">@TempData["Error"]</p>
            <hr />
        }
        @if ((bool)TempData["Delete"])
        {
            <p class="box warning">Tebrikler! Kayıt Başarıyla Silindi.</p>
            <hr />
        }
        
        @(Html.Telerik().Grid(Model)
        .Name("CompanyTypes")
        .DataKeys(dataKeys => dataKeys.Add(c => c.Id))
        .DataBinding(dataBinding => dataBinding.Server()
            .Delete("CompanyTypeDelete", "Company", null))
        .Columns(columns =>
        {
            columns.Bound(o => o.Id).Title("No.").Width(100);
            columns.Bound(o => o.Name).Title("Firma Faaliyet Alanı");
            columns.Command(commands => 
                {                    
                    commands.Custom("viewDetails")
                    .Text("Detay")
                    .Ajax(false)
                    .Action("CompanyTypeRead", "Company", null);
                    commands.Delete().ButtonType(GridButtonType.ImageAndText);
                })
            .Width(200);
        })
        .Sortable()
        .Pageable(paging => paging.PageSize(10))
        .Localizable("tr-TR")
        )
            
        @Html.ActionLink("Firma Faaliyet Alanı Oluştur", "CompanyTypeCreate", null, new { Class = "ym-button ym-add" })        
    </div>
</div>

CSS.OpusForce.UI.Web.MVC/Views/Company/CompanyTypeRead.cshtml
@using CSS.OpusForce.Services.ViewModels;
@model CompanyTypeView

@{
    ViewBag.Title = "Firma Faaliyet Alanı Detay";
    Layout = "~/Views/Shared/_Layout.cshtml";   
}

<div id="header-band" class="bg-blue">    
   @Html.ActionLink("Firmalar", "CompanyTypeList", "Company", null, new { Class = "btnBack" })
   @Html.ActionLink("Anasayfa", "Index", "Home", null, new { Class = "btnHome" })   
   <div class="ym-wrapper">
       <div class="ym-grid top-35">
           <div class="ym-gl">
               <img alt="OpusForce Logo" src="@Url.Content("~/Content/images/logo.png")" />
           </div>
           <div class="ym-gr">
               @Html.ActionLink("Home", "Index", "Home", null, new { Class = "btnLogin" })
           </div>
       </div> 
   </div>           
</div>
<div class="clearfix"></div>
<div id="main">
    <div class="ym-wrapper">   
        <div class="ym-hlist">
          <ul>
            <li>@Html.ActionLink("Firmalar", "CompanyList", "Company", null, null)</li>
            <li class="active">@Html.ActionLink("Firma Faaliyet Alanları", "CompanyTypeList", "Company", null, null)</li>
          </ul>
        </div>
        <hr />

        @if ((bool)TempData["Add"])
        {
            <p class="box success">Tebrikler! Kayıt Başarıyla Oluşturuldu.</p>
            <hr />
        }
        @if ((bool)TempData["Update"])
        {
            <p class="box success">Tebrikler! Kayıt Başarıyla Güncelleştirildi.</p>
            <hr />
        }
        
        <div class="ym-grid ym-gbox">
            <div class="ym-g38 ym-gl"><b>Faaliyet Alanı No.</b></div><div class="ym-g62 ym-gr">: @Model.Id</div>
        </div>
        <div class="ym-grid">
            <hr class="thick" />
        </div>
        <div class="ym-grid ym-gbox">
            <div class="ym-g38 ym-gl"><b>Faaliyet Alanı Adı</b></div><div class="ym-g62 ym-gr">: @Model.Name</div>
        </div>
        <div class="ym-grid">
            <hr class="thick" />
        </div>
        <div class="ym-grid ym-gbox">
            <div class="ym-g38 ym-gl"><b>Faaliyet Alanı Açıklaması</b></div><div class="ym-g62 ym-gr">: @Model.Description</div>
        </div>
        <div class="ym-grid">
            <hr class="thick" />
        </div>
        <div class="ym-grid">
             @Html.ActionLink("Geri dön", "CompanyTypeList", "Company", null, new { Class = "ym-button ym-left-arrow" })
             @Html.ActionLink("Düzenle", "CompanyTypeUpdate", "Company", new { id = Model.Id }, new { Class = "ym-button ym-edit" })
        </div>        
    </div>
</div>

CSS.OpusForce.UI.Web.MVC/Views/Company/CompanyTypeUpdate.cshtml
@using CSS.OpusForce.Services.ViewModels;
@model CompanyTypeView

@{
    ViewBag.Title = "Firma Faaliyet Alanı Düzenleme";
    Layout = "~/Views/Shared/_Layout.cshtml";   
}

<script type="text/javascript">
    $(function () {
        $('form.uniForm').uniform({
            prevent_submit: true
        });
    });
</script>

<div id="header-band" class="bg-blue">    
   @Html.ActionLink("Firmalar", "CompanyTypeList", "Company", null, new { Class = "btnBack" })
   @Html.ActionLink("Anasayfa", "Index", "Home", null, new { Class = "btnHome" })   
   <div class="ym-wrapper">
       <div class="ym-grid top-35">
           <div class="ym-gl">
               <img alt="OpusForce Logo" src="@Url.Content("~/Content/images/logo.png")" />
           </div>
           <div class="ym-gr">
               @Html.ActionLink("Home", "Index", "Home", null, new { Class = "btnLogin" })
           </div>
       </div> 
   </div>           
</div>
<div class="clearfix"></div>
<div id="main">
    <div class="ym-wrapper">   
        <div class="ym-hlist">
          <ul>
            <li>@Html.ActionLink("Firmalar", "CompanyList", "Company", null, null)</li>
            <li class="active">@Html.ActionLink("Firma Faaliyet Alanları", "CompanyTypeList", "Company", null, null)</li>
          </ul>
        </div>
        <hr />
        @using (Html.BeginForm(null, null, FormMethod.Post, new { Class="ym-form ym-columnar" }))
        {   
            @Html.ValidationSummary() 
            
            if (!String.IsNullOrEmpty((string)TempData["Error"]))
            {
                <p class="box error">@TempData["Error"]</p>
                <hr />
            }
            
            <div class="ym-fbox-text">
                <label for="Id">Faaliyet Alanı No.</label>
                @Html.TextBoxFor(c => c.Id, new { @readonly = "readonly" })
            </div>
            
            <div class="ym-fbox-text">
                <label for="Name">Faaliyet Alan Adı</label>
                @Html.TextBoxFor(c => c.Name)
            </div>
            
            <div class="ym-fbox-text">
                <label for="Description">Faaliyet Alanı Açıklaması</label>
                @Html.TextAreaFor(c => c.Description, new { rows = "5" })
            </div>
    
            <div class="ym-fbox-button">
                @Html.ActionLink("Vazgeç ve geri dön", "CompanyTypeRead", "Company", new { Model.Id }, new { Class = "ym-button ym-left-arrow" }) 
                <button class="ym-button ym-save">Güncelle</button>
            </div>   
        }        
    </div>
</div>