CSS.OpusForce.UI.Web.MVC/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CSS.OpusForce.Services.Interfaces;
using CSS.OpusForce.Services.Messaging;
using CSS.OpusForce.Services.ViewModels;


namespace CSS.OpusForce.UI.Web.MVC.Controllers
{
    public class ProjectController : Controller
    {
        private readonly IProjectServices _projectService;
        private readonly ICompanyServices _companyService;

        public ProjectController(IProjectServices projectService, ICompanyServices companyService)
        {
            _projectService = projectService;
            _companyService = companyService;

            ResetInfoMessages();
        }

        private void ResetInfoMessages()
        {
            if (TempData["Error"] == null)
                TempData["Error"] = string.Empty;
            if (TempData["Add"] == null)
                TempData["Add"] = false;
            if (TempData["Update"] == null)
                TempData["Update"] = false;
            if (TempData["Delete"] == null)
                TempData["Delete"] = false;
        }

        /*******************************************************************/
        /*                      Project Actions                            */
        /*******************************************************************/
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult ProjectList()
        {
            // 1. Get Project list
            // 2. View ProjectList (Grid)

            ResetInfoMessages();

            ListProjectsResponse response = _projectService.ListProjects(null);
            return View(response.Projects);
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult ProjectCreate()
        {
            // 1. View ProjectCreate (Empty Form)

            ResetInfoMessages();

            var companies = _companyService.ListCompanies(null).Companies.OrderBy(c => c.Name);
            var companyList = new SelectList(companies, "Id", "Name");
            TempData["Companies"] = companyList;

            var projectTypes = _projectService.ListProjectTypes(null).ProjectTypes.OrderBy(c => c.Name);
            var projectTypeList = new SelectList(projectTypes, "Id", "Name");
            TempData["ProjectTypes"] = projectTypeList;

            var projectStatuses = _projectService.ListProjectStatuses(null).ProjectStatuses.OrderBy(c => c.Name);
            var projectStatusList = new SelectList(projectStatuses, "Id", "Name");
            TempData["projectStatuses"] = projectStatusList;

            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult ProjectCreate(ProjectView view)
        {
            // 1. If ModelState is not valid
            // ------------------------------
            // 1.1. View ProjectCreate (Empty Form)
            // 1.2. Enable ValidationSummary
            // ------------------------------
            // 2. If ExceptionState is true
            // ------------------------------
            // 2.1. View ProjectCreate (Empty Form)
            // 2.2. Enable ErrorBox
            // ------------------------------
            // 3. Set Add to true
            // 4. View ProjectRead
            // 5. View SuccessBox

            ResetInfoMessages();

            var companies = _companyService.ListCompanies(null).Companies.OrderBy(c => c.Name);
            var companyList = new SelectList(companies, "Id", "Name");
            TempData["Companies"] = companyList;

            var projectTypes = _projectService.ListProjectTypes(null).ProjectTypes.OrderBy(c => c.Name);
            var projectTypeList = new SelectList(projectTypes, "Id", "Name");
            TempData["ProjectTypes"] = projectTypeList;

            var projectStatuses = _projectService.ListProjectStatuses(null).ProjectStatuses.OrderBy(c => c.Name);
            var projectStatusList = new SelectList(projectStatuses, "Id", "Name");
            TempData["projectStatuses"] = projectStatusList;

            if (ModelState.IsValid)
            {
                CreateProjectRequest request = new CreateProjectRequest();
                request.Name = view.Name;
                request.Description = view.Description;
                request.CompanyId = view.CompanyId;
                request.ProjectTypeId = view.ProjectTypeId;
                request.ProjectStatusId = view.ProjectStatusId;
                request.StartDate = view.StartDate;
                request.EndDate = view.EndDate;

                CreateProjectResponse response = _projectService.CreateProject(request);

                if (response.ExceptionState)
                {
                    TempData["Error"] = response.ExceptionMessage;
                    return View();
                }

                TempData["Add"] = true;
                return View("ProjectRead", response.Project);
            }
            else
            {
                return View();
            }
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult ProjectRead(int id)
        {
            // 1. Get Project (by Id)
            // 2. View ProjectRead

            ResetInfoMessages();

            ReadProjectRequest request = new ReadProjectRequest();
            request.Id = id;

            ReadProjectResponse response = new ReadProjectResponse();
            response = _projectService.ReadProject(request);

            return View("ProjectRead", response.Project);
        }
        /*******************************************************************/
        /*                    ProjectType Actions                          */
        /*******************************************************************/
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult ProjectTypeList()
        {
            // 1. Get ProjectType list
            // 2. View ProjectTypeList (Grid)

            ResetInfoMessages();

            ListProjectTypesResponse response = _projectService.ListProjectTypes(null);
            return View(response.ProjectTypes);
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult ProjectTypeCreate()
        {
            // 1. View ProjectTypeCreate (Empty Form)

            ResetInfoMessages();

            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult ProjectTypeCreate(ProjectTypeView view)
        {
            // 1. If ModelState is not valid
            // ------------------------------
            // 1.1. View ProjectTypeCreate (Empty Form)
            // 1.2. Enable ValidationSummary
            // ------------------------------
            // 2. If ExceptionState is true
            // ------------------------------
            // 2.1. View ProjectTypeCreate (Empty Form)
            // 2.2. Enable ErrorBox
            // ------------------------------
            // 3. Set Add to true
            // 4. View ProjectTypeRead
            // 5. View SuccessBox

            ResetInfoMessages();

            if (ModelState.IsValid)
            {
                CreateProjectTypeRequest request = new CreateProjectTypeRequest();
                request.Name = view.Name;
                request.Description = view.Description;

                CreateProjectTypeResponse response = _projectService.CreateProjectType(request);

                if (response.ExceptionState)
                {
                    TempData["Error"] = response.ExceptionMessage;
                    return View();
                }

                TempData["Add"] = true;
                return View("ProjectTypeRead", response.ProjectType);
            }
            else
            {
                return View();
            }
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult ProjectTypeRead(int id)
        {
            // 1. Get ProjectType (by Id)
            // 2. View ProjectTypeRead

            ResetInfoMessages();

            ReadProjectTypeRequest request = new ReadProjectTypeRequest();
            request.Id = id;

            ReadProjectTypeResponse response = new ReadProjectTypeResponse();
            response = _projectService.ReadProjectType(request);

            return View("ProjectTypeRead", response.ProjectType);
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult ProjectTypeUpdate(int id)
        {
            // 1. Get ProjectType (by Id)
            // 2. View ProjectType (Filled Form)

            ResetInfoMessages();

            ReadProjectTypeRequest request = new ReadProjectTypeRequest();
            request.Id = id;

            ReadProjectTypeResponse response = new ReadProjectTypeResponse();
            response = _projectService.ReadProjectType(request);

            return View(response.ProjectType);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult ProjectTypeUpdate(ProjectTypeView view)
        {
            // 1. If ModelState is not valid
            // ------------------------------
            // 1.1. View ProjectTypeCreate (Filled Form)
            // 1.2. Enable ValidationSummary
            // ------------------------------
            // 2. If ExceptionState is true
            // ------------------------------
            // 2.1. View ProjectTypeCreate (Filled Form)
            // 2.2. Enable ErrorBox
            // ------------------------------
            // 3. Set Update to true
            // 4. View ProjectTypeDetail
            // 5. View SuccessBox

            ResetInfoMessages();

            if (ModelState.IsValid)
            {
                UpdateProjectTypeRequest request = new UpdateProjectTypeRequest();

CSS.OpusForce.UI.Web.MVC/Views/Project/ProjectCreate.cshtml
@using CSS.OpusForce.Services.ViewModels;
@model ProjectView

@{
    ViewBag.Title = "Proje Ekleme";
    Layout = "~/Views/Shared/_Layout.cshtml";   
}

<script type="text/javascript">
    $(function () {
        $('form.uniForm').uniform({
            prevent_submit: true
        });
    });
</script>

<div id="header-band" class="bg-blue">    
   @Html.ActionLink("Projeler", "ProjectList", "Project", null, new { Class = "btnBack" })
   @Html.ActionLink("Anasayfa", "Index", "Home", null, new { Class = "btnHome" })   
   <div class="ym-wrapper">
       <div class="ym-grid top-35">
           <div class="ym-gl">
               <img alt="OpusForce Logo" src="@Url.Content("~/Content/images/logo.png")" />
           </div>
           <div class="ym-gr">
               @Html.ActionLink("Home", "Index", "Home", null, new { Class = "btnLogin" })
           </div>
       </div> 
   </div>           
</div>
<div class="clearfix"></div>
<div id="main">
    <div class="ym-wrapper">        
        <div class="ym-hlist">
          <ul>
            <li class="active">@Html.ActionLink("Projeler", "ProjectList", "Project", null, null)</li>
            <li>@Html.ActionLink("Proje Türleri", "ProjectTypeList", "Project", null, null)</li>
            <li>@Html.ActionLink("Proje Durumları", "ProjectStatusList", "Project", null, null)</li>
          </ul>
        </div>
        <hr />
        @using (Html.BeginForm(null, null, FormMethod.Post, new { Class="ym-form ym-columnar" }))
        {   
            @Html.ValidationSummary() 
            
            if (!String.IsNullOrEmpty((string)TempData["Error"]))
            {
                <p class="box error">@TempData["Error"]</p>
                <hr />
            }
            
            <div class="ym-fbox-text">
                <label for="Name">Proje Adı</label>
                @Html.TextBoxFor(c => c.Name)
            </div>
            
            <div class="ym-fbox-text">
                <label for="Description">Proje Açıklaması</label>
                @Html.TextAreaFor(c => c.Description, new { rows = "5" })
            </div>
            
            <div class="ym-fbox-select">
                <label for="CompanyId">Projenin Bağlı Olduğu Firma</label>
                @Html.DropDownListFor(c => c.CompanyId, (SelectList)TempData["Companies"], "-Seçiniz-")
            </div>
            
            <div class="ym-fbox-select">
                <label for="ProjectTypeId">Projenin Türü</label>
                @Html.DropDownListFor(c => c.ProjectTypeId, (SelectList)TempData["ProjectTypes"], "-Seçiniz-")
            </div>
            
            <div class="ym-fbox-select">
                <label for="ProjectStatusId">Projenin Bağlı Olduğu Firma</label>
                @Html.DropDownListFor(c => c.ProjectStatusId, (SelectList)TempData["ProjectStatuses"], "-Seçiniz-")
            </div>
            
            <div class="ym-fbox-select">
                <label for="StartDate">Projenin Başlangıç Tarihi</label>
                @(Html.Telerik().DateTimePickerFor(c => c.StartDate)
                )
            </div>
            
            <div class="ym-fbox-select">
                <label for="EndDate">Projenin Bitiş Tarihi</label>
                @(Html.Telerik().DateTimePickerFor(c => c.EndDate)
                )
            </div>
    
            <div class="ym-fbox-button">
                @Html.ActionLink("Vazgeç ve geri dön", "ProjectList", "Project", null, new { Class = "ym-button ym-left-arrow" }) 
                <button class="ym-button ym-add">Kaydet</button>
            </div>   
        }        
    </div>
</div>

CSS.OpusForce.UI.Web.MVC/Views/Project/ProjectList.cshtml
@using CSS.OpusForce.Services.ViewModels;
@model IEnumerable<ProjectSummaryView>

@{
    ViewBag.Title = "Proje Listesi";
    Layout = "~/Views/Shared/_Layout.cshtml";   
}

<div id="header-band" class="bg-blue">    
   @Html.ActionLink("Projeler", "ProjectList", "Project", null, new { Class = "btnBack" })
   @Html.ActionLink("Anasayfa", "Index", "Home", null, new { Class = "btnHome" })   
   <div class="ym-wrapper">
       <div class="ym-grid top-35">
           <div class="ym-gl">
               <img alt="OpusForce Logo" src="@Url.Content("~/Content/images/logo.png")" />
           </div>
           <div class="ym-gr">
               @Html.ActionLink("Home", "Index", "Home", null, new { Class = "btnLogin" })
           </div>
       </div> 
   </div>           
</div>
<div class="clearfix"></div>
<div id="main">
    <div class="ym-wrapper">        
        <div class="ym-hlist">
          <ul>
            <li class="active">@Html.ActionLink("Projeler", "ProjectList", "Project", null, null)</li>
            <li>@Html.ActionLink("Proje Türleri", "ProjectTypeList", "Project", null, null)</li>
            <li>@Html.ActionLink("Proje Durumları", "ProjectStatusList", "Project", null, null)</li>
          </ul>
        </div>
        <hr />

        @if (!String.IsNullOrEmpty((string)TempData["Error"]))
        {
            <p class="box error">@TempData["Error"]</p>
            <hr />
        }
        @if ((bool)TempData["Delete"])
        {
            <p class="box warning">Tebrikler! Kayıt Başarıyla Silindi.</p>
            <hr />
        }
        
        @(Html.Telerik().Grid(Model)
        .Name("Projects")
        .DataKeys(dataKeys => dataKeys.Add(c => c.Id))
        .DataBinding(dataBinding => dataBinding.Server()
            .Delete("ProjectDelete", "Project", null))
        .Columns(columns =>
        {
            columns.Bound(o => o.Id).Title("No.").Width(100);
            columns.Bound(o => o.Name).Title("Proje Adı");
            columns.Command(commands => 
                {                    
                    commands.Custom("viewDetails")
                    .Text("Detay")
                    .Ajax(false)
                    .Action("ProjectRead", "Project", null);
                    commands.Delete().ButtonType(GridButtonType.ImageAndText);
                })
            .Width(200);
        })
        .Sortable()
        .Pageable(paging => paging.PageSize(10))
        .Localizable("tr-TR")
        )
            
        @Html.ActionLink("Proje Oluştur", "ProjectCreate", null, new { Class = "ym-button ym-add" })        
    </div>
</div>

CSS.OpusForce.UI.Web.MVC/Views/Project/ProjectRead.cshtml
@using CSS.OpusForce.Services.ViewModels;
@model ProjectView

@{
    ViewBag.Title = "Proje Detay";
    Layout = "~/Views/Shared/_Layout.cshtml";   
}

<div id="header-band" class="bg-blue">    
   @Html.ActionLink("Projeler", "ProjectList", "Project", null, new { Class = "btnBack" })
   @Html.ActionLink("Anasayfa", "Index", "Home", null, new { Class = "btnHome" })   
   <div class="ym-wrapper">
       <div class="ym-grid top-35">
           <div class="ym-gl">
               <img alt="OpusForce Logo" src="@Url.Content("~/Content/images/logo.png")" />
           </div>
           <div class="ym-gr">
               @Html.ActionLink("Home", "Index", "Home", null, new { Class = "btnLogin" })
           </div>
       </div> 
   </div>           
</div>
<div class="clearfix"></div>
<div id="main">
    <div class="ym-wrapper">        
        <div class="ym-hlist">
          <ul>
            <li class="active">@Html.ActionLink("Projeler", "ProjectList", "Project", null, null)</li>
            <li>@Html.ActionLink("Proje Türleri", "ProjectTypeList", "Project", null, null)</li>
            <li>@Html.ActionLink("Proje Durumları", "ProjectStatusList", "Project", null, null)</li>
          </ul>
        </div>
        <hr />

        @if ((bool)TempData["Add"])
        {
            <p class="box success">Tebrikler! Kayıt Başarıyla Oluşturuldu.</p>
            <hr />
        }
        @if ((bool)TempData["Update"])
        {
            <p class="box success">Tebrikler! Kayıt Başarıyla Güncelleştirildi.</p>
            <hr />
        }
        
        <div class="ym-grid ym-gbox">
            <div class="ym-g38 ym-gl"><b>Proje No.</b></div><div class="ym-g62 ym-gr">: @Model.Id</div>
        </div>
        <div class="ym-grid">
            <hr class="thick" />
        </div>
        <div class="ym-grid ym-gbox">
            <div class="ym-g38 ym-gl"><b>Proje Adı</b></div><div class="ym-g62 ym-gr">: @Model.Name</div>
        </div>
        <div class="ym-grid">
            <hr class="thick" />
        </div>
        <div class="ym-grid ym-gbox">
            <div class="ym-g38 ym-gl"><b>Proje Açıklaması</b></div><div class="ym-g62 ym-gr">: @Model.Description</div>
        </div>
        <div class="ym-grid">
            <hr class="thick" />
        </div>
        <div class="ym-grid ym-gbox">
            <div class="ym-g38 ym-gl"><b>Projenin Bağlı Olduğu Firma</b></div><div class="ym-g62 ym-gr">: @Model.CompanyName</div>
        </div>
        <div class="ym-grid">
            <hr class="thick" />
        </div>
        <div class="ym-grid ym-gbox">
            <div class="ym-g38 ym-gl"><b>Proje Türü</b></div><div class="ym-g62 ym-gr">: @Model.ProjectTypeName</div>
        </div>
        <div class="ym-grid">
            <hr class="thick" />
        </div>
        <div class="ym-grid ym-gbox">
            <div class="ym-g38 ym-gl"><b>Proje Durumu</b></div><div class="ym-g62 ym-gr">: @Model.ProjectStatusName</div>
        </div>
        <div class="ym-grid">
            <hr class="thick" />
        </div>
        <div class="ym-grid ym-gbox">
            <div class="ym-g38 ym-gl"><b>Proje Başlangıç Tarihi</b></div><div class="ym-g62 ym-gr">: @Model.StartDate</div>
        </div>
        <div class="ym-grid">
            <hr class="thick" />
        </div>
        <div class="ym-grid ym-gbox">
            <div class="ym-g38 ym-gl"><b>Proje Bitiş Tarihi</b></div><div class="ym-g62 ym-gr">: @Model.EndDate</div>
        </div>
        <div class="ym-grid">
            <hr class="thick" />
        </div>
        <div class="ym-grid">
             @Html.ActionLink("Geri dön", "ProjectList", "Project", null, new { Class = "ym-button ym-left-arrow" })
             @Html.ActionLink("Düzenle", "ProjectUpdate", "Project", new { id = Model.Id }, new { Class = "ym-button ym-edit" })
        </div>        
    </div>
</div>

CSS.OpusForce.UI.Web.MVC/Views/Project/ProjectStatusCreate.cshtml
@using CSS.OpusForce.Services.ViewModels;
@model ProjectStatusView

@{
    ViewBag.Title = "Proje Durumu Ekleme";
    Layout = "~/Views/Shared/_Layout.cshtml";   
}

<script type="text/javascript">
    $(function () {
        $('form.uniForm').uniform({
            prevent_submit: true
        });
    });
</script>

<div id="header-band" class="bg-blue">    
   @Html.ActionLink("Projeler", "ProjectList", "Project", null, new { Class = "btnBack" })
   @Html.ActionLink("Anasayfa", "Index", "Home", null, new { Class = "btnHome" })   
   <div class="ym-wrapper">
       <div class="ym-grid top-35">
           <div class="ym-gl">
               <img alt="OpusForce Logo" src="@Url.Content("~/Content/images/logo.png")" />
           </div>
           <div class="ym-gr">
               @Html.ActionLink("Home", "Index", "Home", null, new { Class = "btnLogin" })
           </div>
       </div> 
   </div>           
</div>
<div class="clearfix"></div>
<div id="main">
    <div class="ym-wrapper">        
        <div class="ym-hlist">
          <ul>
            <li>@Html.ActionLink("Projeler", "ProjectList", "Project", null, null)</li>
            <li>@Html.ActionLink("Proje Türleri", "ProjectTypeList", "Project", null, null)</li>
            <li class="active">@Html.ActionLink("Proje Durumları", "ProjectStatusList", "Project", null, null)</li>
          </ul>
        </div>
        <hr />
        @using (Html.BeginForm(null, null, FormMethod.Post, new { Class="ym-form ym-columnar" }))
        {   
            @Html.ValidationSummary() 
            
            if (!String.IsNullOrEmpty((string)TempData["Error"]))
            {
                <p class="box error">@TempData["Error"]</p>
                <hr />
            }
            
            <div class="ym-fbox-text">
                <label for="Name">Proje Durumu Adı</label>
                @Html.TextBoxFor(c => c.Name)
            </div>
            
            <div class="ym-fbox-text">
                <label for="Description">Proje Durumu Açıklaması</label>
                @Html.TextAreaFor(c => c.Description, new { rows = "5" })
            </div>
    
            <div class="ym-fbox-button">
                @Html.ActionLink("Vazgeç ve geri dön", "ProjectStatusList", "Project", null, new { Class = "ym-button ym-left-arrow" }) 
                <button class="ym-button ym-add">Kaydet</button>
            </div>   
        }        
    </div>
</div>

CSS.OpusForce.UI.Web.MVC/Views/Project/ProjectStatusList.cshtml
@using CSS.OpusForce.Services.ViewModels;
@model IEnumerable<ProjectStatusSummaryView>

@{
    ViewBag.Title = "Proje Durumları Listesi";
    Layout = "~/Views/Shared/_Layout.cshtml";   
}

<div id="header-band" class="bg-blue">    
   @Html.ActionLink("Projeler", "ProjectList", "Project", null, new { Class = "btnBack" })
   @Html.ActionLink("Anasayfa", "Index", "Home", null, new { Class = "btnHome" })   
   <div class="ym-wrapper">
       <div class="ym-grid top-35">
           <div class="ym-gl">
               <img alt="OpusForce Logo" src="@Url.Content("~/Content/images/logo.png")" />
           </div>
           <div class="ym-gr">
               @Html.ActionLink("Home", "Index", "Home", null, new { Class = "btnLogin" })
           </div>
       </div> 
   </div>           
</div>
<div class="clearfix"></div>
<div id="main">
    <div class="ym-wrapper">        
        <div class="ym-hlist">
          <ul>
            <li>@Html.ActionLink("Projeler", "ProjectList", "Project", null, null)</li>
            <li>@Html.ActionLink("Proje Türleri", "ProjectTypeList", "Project", null, null)</li>
            <li class="active">@Html.ActionLink("Proje Durumları", "ProjectStatusList", "Project", null, null)</li>
          </ul>
        </div>
        <hr />

        @if (!String.IsNullOrEmpty((string)TempData["Error"]))
        {
            <p class="box error">@TempData["Error"]</p>
            <hr />
        }
        @if ((bool)TempData["Delete"])
        {
            <p class="box warning">Tebrikler! Kayıt Başarıyla Silindi.</p>
            <hr />
        }
        
        @(Html.Telerik().Grid(Model)
        .Name("ProjectStatuses")
        .DataKeys(dataKeys => dataKeys.Add(c => c.Id))
        .DataBinding(dataBinding => dataBinding.Server()
            .Delete("ProjectStatusDelete", "Project", null))
        .Columns(columns =>
        {
            columns.Bound(o => o.Id).Title("No.").Width(100);
            columns.Bound(o => o.Name).Title("Proje Durumu");
            columns.Command(commands => 
                {                    
                    commands.Custom("viewDetails")
                    .Text("Detay")
                    .Ajax(false)
                    .Action("ProjectStatusRead", "Project", null);
                    commands.Delete().ButtonType(GridButtonType.ImageAndText);
                })
            .Width(200);
        })
        .Sortable()
        .Pageable(paging => paging.PageSize(10))
        .Localizable("tr-TR")
        )
            
        @Html.ActionLink("Proje Durumu Oluştur", "ProjectStatusCreate", null, new { Class = "ym-button ym-add" })        
    </div>
</div>

CSS.OpusForce.UI.Web.MVC/Views/Project/ProjectStatusRead.cshtml
@using CSS.OpusForce.Services.ViewModels;
@model ProjectStatusView

@{
    ViewBag.Title = "Proje Durumu Detay";
    Layout = "~/Views/Shared/_Layout.cshtml";   
}

<div id="header-band" class="bg-blue">    
   @Html.ActionLink("Projeler", "ProjectList", "Project", null, new { Class = "btnBack" })
   @Html.ActionLink("Anasayfa", "Index", "Home", null, new { Class = "btnHome" })   
   <div class="ym-wrapper">
       <div class="ym-grid top-35">
           <div class="ym-gl">
               <img alt="OpusForce Logo" src="@Url.Content("~/Content/images/logo.png")" />
           </div>
           <div class="ym-gr">
               @Html.ActionLink("Home", "Index", "Home", null, new { Class = "btnLogin" })
           </div>
       </div> 
   </div>           
</div>
<div class="clearfix"></div>
<div id="main">
    <div class="ym-wrapper">        
        <div class="ym-hlist">
          <ul>
            <li>@Html.ActionLink("Projeler", "ProjectList", "Project", null, null)</li>
            <li>@Html.ActionLink("Proje Türleri", "ProjectTypeList", "Project", null, null)</li>
            <li class="active">@Html.ActionLink("Proje Durumları", "ProjectStatusList", "Project", null, null)</li>
          </ul>
        </div>
        <hr />

        @if ((bool)TempData["Add"])
        {
            <p class="box success">Tebrikler! Kayıt Başarıyla Oluşturuldu.</p>
            <hr />
        }
        @if ((bool)TempData["Update"])
        {
            <p class="box success">Tebrikler! Kayıt Başarıyla Güncelleştirildi.</p>
            <hr />
        }
        
        <div class="ym-grid ym-gbox">
            <div class="ym-g38 ym-gl"><b>Proje Durumu No.</b></div><div class="ym-g62 ym-gr">: @Model.Id</div>
        </div>
        <div class="ym-grid">
            <hr class="thick" />
        </div>
        <div class="ym-grid ym-gbox">
            <div class="ym-g38 ym-gl"><b>Proje Durumu Adı</b></div><div class="ym-g62 ym-gr">: @Model.Name</div>
        </div>
        <div class="ym-grid">
            <hr class="thick" />
        </div>
        <div class="ym-grid ym-gbox">
            <div class="ym-g38 ym-gl"><b>Proje Durumu Açıklaması</b></div><div class="ym-g62 ym-gr">: @Model.Description</div>
        </div>
        <div class="ym-grid">
            <hr class="thick" />
        </div>
        <div class="ym-grid">
             @Html.ActionLink("Geri dön", "ProjectStatusList", "Project", null, new { Class = "ym-button ym-left-arrow" })
             @Html.ActionLink("Düzenle", "ProjectStatusUpdate", "Project", new { id = Model.Id }, new { Class = "ym-button ym-edit" })
        </div>        
    </div>
</div>